#!/bin/bash
# Build menu_rom.vh -- the OSD menu that sysctrl streams to FPGA-Companion on
# CMD 8. The companion gunzips it and renders the menu described inside.
#
#   ./make_menu_rom.sh
#
# The XML is minified first: comments and indentation are for whoever reads the
# file in the repo, and they do not fit in a 1K ROM once compressed.
#
# Output is a Verilog case statement rather than a .hex for $readmemh. That is
# deliberate: $readmemh resolves its path against the synthesis working
# directory, which differs between the Gowin IDE and build.tcl, and a path it
# cannot resolve yields a silently zero-filled ROM -- which looks exactly like
# a working build whose OSD does nothing.
set -euo pipefail
cd "$(dirname "$0")"

SRC=msxnano.xml
OUT=menu_rom.vh
CAP=1024

python3 - "$SRC" > /tmp/menu_min.xml <<'PY'
import re, sys
x = open(sys.argv[1], encoding='utf-8').read()
x = re.sub(r'<!--.*?-->', '', x, flags=re.S)
x = re.sub(r'>\s+<', '><', x)
x = re.sub(r'[ \t]+', ' ', x)
sys.stdout.write(x.strip())
PY

gzip -9 -n -c /tmp/menu_min.xml > /tmp/menu_min.xml.gz
SIZE=$(wc -c < /tmp/menu_min.xml.gz | tr -d ' ')

if [ "$SIZE" -gt "$CAP" ]; then
    echo "ERROR: $SIZE bytes gzipped, ROM holds $CAP."
    echo "Trim the menu, or widen menu_rom_addr in sys_ctrl.v."
    exit 1
fi

python3 - /tmp/menu_min.xml.gz "$OUT" "$SIZE" <<'PY'
import sys
data = open(sys.argv[1], 'rb').read()
out, size = sys.argv[2], int(sys.argv[3])
with open(out, 'w') as f:
    f.write("// Generated by make_menu_rom.sh -- do not edit.\n")
    f.write("// gzipped msxnano.xml, streamed to FPGA-Companion on sysctrl CMD 8.\n")
    f.write(f"// {size} bytes. Regenerate after editing msxnano.xml.\n")
    f.write("case (menu_rom_addr)\n")
    for i, b in enumerate(data):
        f.write(f"  10'd{i}: menu_rom_data <= 8'h{b:02X};\n")
    f.write("  default: menu_rom_data <= 8'h00;\n")
    f.write("endcase\n")
PY

echo "$OUT: $SIZE bytes gzipped, $((CAP - SIZE)) spare"
